### ISSUE TITLE
ImportError: No module named Image

### ISSUE THREAD

**Issue by billmetangmo** [Levis0045/MetaLex-vagrant#29]
When trying to execute python runMetaLex.py -h, I got the error : 

Traceback (most recent call last):
  File "runMetaLex.py", line 28, in <module>
    import MetaLex as dico
  File "../MetaLex/__init__.py", line 36, in <module>
    from .dicOcrText    import *
  File "../MetaLex/dicOcrText/__init__.py", line 42, in <module>
    from normalizeImage  import enhanceImages, getImages
  File "../MetaLex/dicOcrText/normalizeImage.py", line 53, in <module>
    import Image, os
ImportError: No module named Image

**Comment by Levis0045** [comment]
Thank @billmetangmo  we are resolved the problem !

**Comment by billmetangmo** [comment]
It works now . Thanks :) !
